# Generated by Django 5.2.17 on 2026-08-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('delivering', 'Доставляется'), ('done', 'Выполнен')], db_index=True, default='new', max_length=20, verbose_name='статус'),
        ),
    ]
