# Generated by Django 5.2.17 on 2026-09-14 15:50

import django.core.validators
import django.db.models.deletion
import foodcartapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_delete_geocache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'позиция заказа', 'verbose_name_plural': 'позиции заказа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'ресторан', 'verbose_name_plural': 'рестораны'},
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(max_length=20, validators=[foodcartapp.validators.validate_phonenumber], verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='foodcartapp.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='контактный телефон'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='название'),
        ),
    ]
